### ISSUE TITLE
Red 'Attaching' symbol on harvesters?

### ISSUE THREAD

**Issue by fdanapfel** [stijnwop/manualAttaching#14] opened 2018-03-14 18:32 UTC
Since version 1.3.0.0 I'm getting a red attaching symbol after attaching the header and the PTO on a harvester, but the harvester works as usual. I checked al around the machine to see if I missed to attach something, but couldn't find anything.

I've tested this with various harvesters on a new career without any other mods activated on GCV, and all of them show the same behaviour. It doesn't happen on other machines with PTOs, like manure spreaders, though.

Is this intended?

**Comment by H4nnib4l22** [comment] 2018-03-15 06:45
Hello, I have the same problem. No matter which combine harvester, it all occurs.

**Comment by stijnwop** [comment] 2018-03-19 10:29
I see, confirmed it. No it's not intended.

**Comment by stijnwop** [comment] 2018-04-07 21:43
Fixed with 4cebf25

**Closed by stijnwop** 2018-04-07 21:43 UTC
Labels: bug
